#pragma once

#define ACOUSTICGRANDPIANO	0
#define BRIGHTACOUSTICPIANO 1
#define ELECTRICGRANDPIANO	2
#define HONKYTONKPIANO		3
#define ELECTRICPIANO1		4
#define ELECTRICPIANO2		5
#define HARPSICHORD			6
#define CLAVINET			7

#define VIOLIN		40
#define VIOLA		41
#define CELLO		42
#define CONTRABASS	43

#define TREMOLOSTRINGS		44
#define PIZZICATOSTRINGS	45
#define ORCHESTRALHARP		46