#pragma once
#define PC_C    0
#define PC_Cs   1
#define PC_Db   1
#define PC_D    2
#define PC_Ds   3
#define PC_Eb   3
#define PC_E    4
#define PC_F    5
#define PC_Fs   6
#define PC_Gb   6
#define PC_G    7
#define PC_Gs   8
#define PC_Ab   8
#define PC_A    9
#define PC_As   10
#define PC_Bb   10
#define PC_B    11

#define PC_STR_C    "C"
#define PC_STR_Cs   "Cs"
#define PC_STR_Db   "Db"
#define PC_STR_D    "D"
#define PC_STR_Ds   "Ds"
#define PC_STR_Eb   "Eb"
#define PC_STR_E    "E"
#define PC_STR_F    "F"
#define PC_STR_Fs   "Fs"
#define PC_STR_Gb   "Gb"
#define PC_STR_G    "G"
#define PC_STR_Gs   "Gs"
#define PC_STR_Ab   "Ab"
#define PC_STR_A    "A"
#define PC_STR_As   "As"
#define PC_STR_Bb   "Bb"
#define PC_STR_B    "B"
